package humantrackingperformancemetrics;

/**
 * Class of frame statistics. 
 * These are generated by HTPM_JFrame.updateStats()
 * 
 * Abbreviations:
 *  sut -- system under test
 *  gt  -- ground truth
 * 
 * @author Will Shackleford<shackle@nist.gov>
 */
public class FrameStats {
    
    /**
     * Area in square meters that both ground truth and system under test 
     * consider occupied.
     */
    public double true_occupied_area = 0.0;
    
    
    /**
     * Area in square meters that both system under test 
     * considers occupied but ground truth does not.
     */
    public double false_occupied_area = 0.0;
    
    /**
     * Area in square meters that both ground truth and system under test 
     * consider clear. (within 10m x 10m area of interest.)
     */
    public double true_clear_area = 0.0;
    
    /**
     * Area in square meters that system under test 
     * consider clears but the ground truth does not.
     * (within 10m x 10m area of interest.)
     */
    public double false_clear_area = 0.0;
    
    /**
     * Area in square meters that ground truth considers occupied.
     * (within 10m x 10m area of interest.
     */
    public double total_gt_occupied_area = 0.0;
    
    /**
     * Area in square meters that system under test considers occupied.
     * (within 10m x 10m area of interest.
     */
    public double total_sut_occupied_area = 0.0;
    
    /**
     * Average distance between each ground-truth location and closest system
     * under test location.
     */
    public double avg_gt_to_sut_dist = 0.0;
    
    /**
     * Average distance between each system under test location and closest
     * ground-truth location.
     */
    public double avg_sut_to_gt_dist = 0.0;
    
    /**
     * Maximum distance between each ground-truth location and closest system
     * under test location.
     */
    public double max_gt_to_sut_dist = 0.0;
    
    /**
     * Maximum distance between each system under test location and closest
     * ground-truth location.
     */
    public double max_sut_to_gt_dist = 0.0;
    
    /**
     * Total distance between each system under test location and closest
     * ground-truth location.
     */
    public double total_gt_to_sut_dist = 0.0;
    
    /**
     * Total distance between each system under test location and closest
     * ground-truth location.
     */
    public double total_sut_to_gt_dist = 0.0;
    
    /**
     * Number of people( or recievers or trackables) detected by system-under-test.
     */
    public int sut_human_count = 0;
    
    /**
     * Number of people( or recievers or trackables) detected by ground-truth.
     */
    public int gt_human_count = 0; 
}
